try {
    throw Exception(data)
} catch (e: Exception) {
    handleException(data)
} final {

}